import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import kleur from "kleur";
import {
  SYSTEMD_OPERATION_TIMEOUT_MS,
  SYSTEMD_TAILSCALE_BOOT_WAIT_SECONDS,
  SYSTEMD_USER_UNIT_NAME,
} from "../constants.js";
import { cliError, exitCodeForCliError } from "../errors.js";
import { getSystemdUserUnitDir, getSystemdUserUnitPath } from "../paths.js";
import { cliEntry } from "../utils/cli-entry.js";
import { removeTailscaleServe } from "../utils/tailscale.js";
import { reportCliError } from "../utils/report-cli-error.js";
import { setupShellCompletions, teardownShellCompletions } from "../utils/shell-completions.js";
import type { InstallOptions } from "./install.js";
import { reportCdpAvailability, setupTailscaleServe } from "./install-service-setup.js";

const execFileAsync = promisify(execFile);

interface SystemdUnitContentInput {
  port: number;
  host: string;
  // Absolute node binary that runs the daemon (process.execPath at install).
  execPath: string;
  // Absolute entry the daemon loads (the cli package's dist/index.js).
  cliEntry: string;
  // Seconds ExecStartPre waits for tailscaled before booting anyway.
  tailscaleBootWaitSeconds: number;
}

// The Linux equivalent of buildPlistContent: a systemd **user** unit (mirrors
// macOS LaunchAgents — per-user, starts at login / lingers at boot) rather
// than a system unit, so no root is required and state stays in ~/.localterm.
// Crash-only restart (Restart=on-failure === KeepAlive.SuccessfulExit=false):
// the daemon restarts on crash but a clean stop (localterm stop → SIGTERM →
// exit 0) stays stopped. ExecStartPre only waits for tailscale when it's
// installed (`command -v tailscale`), so a pure loopback/ssh-tunnel VPS with no
// tailscale isn't blocked at boot; when it is installed, the wait lets the
// daemon resolve the tailnet URL via `tailscale serve status` so setPublicUrl
// trusts the *.ts.net host before the first request lands.
export const buildSystemdUnitContent = (input: SystemdUnitContentInput): string => {
  // node dir first (a user-installed node shadows system node, matching the
  // launchd plist) then the standard system bins; dedupe so a node living in
  // /usr/local/bin or /usr/bin isn't listed twice.
  const pathEntries = [
    path.dirname(input.execPath),
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ];
  const pathEnv = [...new Set(pathEntries)].join(":");
  return `# Generated by \`localterm install\`. Manage with \`systemctl --user\`.
[Unit]
Description=localterm terminal daemon
Documentation=https://github.com/monotykamary/localterm
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
Environment=HOME=%h
Environment=PATH=${pathEnv}
ExecStartPre=/bin/sh -c 'command -v tailscale >/dev/null 2>&1 || exit 0; for i in $(seq 1 ${input.tailscaleBootWaitSeconds}); do tailscale status --json >/dev/null 2>&1 && exit 0; sleep 1; done; exit 0'
ExecStart=${input.execPath} ${input.cliEntry} start --foreground --port ${input.port} --host ${input.host}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
`;
};

type SystemctlResult = { ok: true } | { ok: false; missing: boolean; message: string };

const runSystemctl = async (args: string[]): Promise<SystemctlResult> => {
  try {
    await execFileAsync("systemctl", ["--user", ...args], {
      timeout: SYSTEMD_OPERATION_TIMEOUT_MS,
    });
    return { ok: true };
  } catch (error) {
    const missing = error instanceof Error && (error as NodeJS.ErrnoException).code === "ENOENT";
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, missing, message };
  }
};

const enableSystemdUserUnit = async (): Promise<void> => {
  console.log();
  console.log(kleur.cyan("systemd  — enable + start the user service"));
  const reload = await runSystemctl(["daemon-reload"]);
  if (!reload.ok) {
    if (reload.missing) {
      console.warn(kleur.yellow("  ⚠ systemctl not found on PATH"));
      console.warn(kleur.dim("    the unit file was written; start it with:"));
      console.warn(
        kleur.dim("    systemctl --user daemon-reload && systemctl --user enable --now localterm"),
      );
    } else {
      console.warn(kleur.yellow(`  ⚠ systemctl --user daemon-reload failed: ${reload.message}`));
      console.warn(
        kleur.dim(
          "    no systemd user session? run the commands above manually, and `sudo loginctl enable-linger $USER` so the service starts at boot without an active session",
        ),
      );
    }
    return;
  }
  const enable = await runSystemctl(["enable", "--now", SYSTEMD_USER_UNIT_NAME]);
  if (!enable.ok) {
    console.warn(kleur.yellow(`  ⚠ systemctl --user enable --now failed: ${enable.message}`));
    console.warn(kleur.dim("    run manually: systemctl --user enable --now localterm"));
    return;
  }
  console.log(kleur.green("  ✔ service enabled and started (restarts on crash)"));
  console.log(
    kleur.dim("    for boot without an active session: sudo loginctl enable-linger $USER"),
  );
};

export const runInstallLinux = async (options: InstallOptions): Promise<void> => {
  const unitDir = getSystemdUserUnitDir();
  mkdirSync(unitDir, { recursive: true });
  const unitPath = getSystemdUserUnitPath();

  const content = buildSystemdUnitContent({
    port: options.port,
    host: options.host,
    execPath: process.execPath,
    cliEntry,
    tailscaleBootWaitSeconds: SYSTEMD_TAILSCALE_BOOT_WAIT_SECONDS,
  });
  writeFileSync(unitPath, content, "utf8");

  console.log(kleur.green(`✔ systemd user unit installed`));
  console.log(`  unit:    ${kleur.dim(unitPath)}`);
  console.log(`  node:    ${kleur.dim(process.execPath)}`);
  console.log(`  entry:   ${kleur.dim(cliEntry)}`);
  console.log(`  port:    ${options.port}`);
  console.log(`  host:    ${options.host}`);
  console.log();
  console.log(
    `  ${kleur.bold("WantedBy=default.target")} + ${kleur.bold("Restart=on-failure")} — localterm will:`,
  );
  console.log(`    • start at login (and at boot with \`loginctl enable-linger\`)`);
  console.log(`    • restart immediately if it crashes`);

  await enableSystemdUserUnit();
  await setupTailscaleServe(options.port);
  await reportCdpAvailability();
  await setupShellCompletions();
  console.log();
  console.log(`  remove with ${kleur.bold("localterm uninstall")}`);
};

export const runUninstallLinux = async (): Promise<void> => {
  const unitPath = getSystemdUserUnitPath();

  if (existsSync(unitPath)) {
    const disable = await runSystemctl(["disable", "--now", SYSTEMD_USER_UNIT_NAME]);
    if (!disable.ok) {
      if (disable.missing) {
        console.log(kleur.dim("systemctl not found on PATH; removing the unit file only."));
      } else {
        console.warn(kleur.yellow(`  ⚠ systemctl --user disable --now failed: ${disable.message}`));
      }
    }
  }

  await removeTailscaleServe();
  await teardownShellCompletions();

  if (!existsSync(unitPath)) {
    console.log(kleur.dim("systemd user unit is not installed."));
    return;
  }

  try {
    unlinkSync(unitPath);
  } catch (unlinkError) {
    const message = unlinkError instanceof Error ? unlinkError.message : String(unlinkError);
    const removeFailError = cliError.installFailed(`failed to remove ${unitPath}: ${message}`);
    reportCliError(removeFailError);
    process.exit(exitCodeForCliError(removeFailError));
    return;
  }

  const reload = await runSystemctl(["daemon-reload"]);
  if (!reload.ok && !reload.missing) {
    console.warn(kleur.dim(`  ⚠ systemctl --user daemon-reload failed: ${reload.message}`));
  }

  console.log(kleur.green("✔ systemd user unit uninstalled"));
  console.log(`  removed ${kleur.dim(unitPath)}`);
};
