import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import kleur from "kleur";
import {
  DAEMON_BASE_PATH,
  LAUNCHD_LABEL,
  PORTLESS_RESOLVE_TIMEOUT_MS,
  PORTLESS_SERVICE_TIMEOUT_MS,
  SYSTEMD_OPERATION_TIMEOUT_MS,
  SYSTEMD_TAILSCALE_BOOT_WAIT_SECONDS,
  SYSTEMD_USER_UNIT_NAME,
  TAILSCALE_HTTPS_PORT,
  CDP_REMOTE_DEBUGGING_HINT,
} from "../constants.js";
import { cliError, type CliError, exitCodeForCliError } from "../errors.js";
import {
  getLaunchdPlistPath,
  getStateDirectory,
  getSystemdUserUnitDir,
  getSystemdUserUnitPath,
} from "../paths.js";
import { cliEntry } from "../utils/cli-entry.js";
import { isPortlessMissing, isPortlessProxyLive } from "../utils/portless.js";
import { configureTailscaleServe, removeTailscaleServe } from "../utils/tailscale.js";
import { probeCdpAvailability } from "../utils/probe-cdp-availability.js";
import { readConfiguredCdpPort } from "../utils/read-configured-cdp-port.js";
import { reportCliError } from "../utils/report-cli-error.js";
import { setupShellCompletions, teardownShellCompletions } from "../utils/shell-completions.js";
import { writeCommandSpec } from "../utils/command-spec.js";

const execFileAsync = promisify(execFile);

export interface InstallOptions {
  port: number;
  host: string;
  portlessDir?: string;
}

const escapePlistString = (value: string): string =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export const buildPlistContent = (options: InstallOptions): string => {
  const stateDirectory = getStateDirectory();
  const logPath = path.join(stateDirectory, "server.log");
  // Minimal system PATH + the daemon's own node dir + the portless dir (the
  // latter two captured at install); see DAEMON_BASE_PATH for why the full user
  // PATH must not be baked. node is needed because `portless` shebangs
  // `#!/usr/bin/env node`.
  const nodeDir = path.dirname(process.execPath);
  const pathParts = [DAEMON_BASE_PATH, nodeDir];
  if (options.portlessDir) pathParts.push(options.portlessDir);
  const pathEnv = pathParts.join(":");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LAUNCHD_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${process.execPath}</string>
        <string>${cliEntry}</string>
        <string>start</string>
        <string>--port</string>
        <string>${options.port}</string>
        <string>--host</string>
        <string>${options.host}</string>
        <string>--foreground</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>${logPath}</string>
    <key>StandardErrorPath</key>
    <string>${logPath}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${os.homedir()}</string>
        <key>PATH</key>
        <string>${escapePlistString(pathEnv)}</string>
    </dict>
</dict>
</plist>
`;
};

export interface SystemdUnitContentInput {
  port: number;
  host: string;
  // Absolute node binary that runs the daemon (process.execPath at install).
  execPath: string;
  // Absolute entry the daemon loads (the cli package's dist/index.js).
  cliEntry: string;
  // Seconds ExecStartPre waits for tailscaled before booting anyway.
  tailscaleBootWaitSeconds: number;
}

// The Linux equivalent of buildPlistContent: a systemd **user** unit (mirrors
// macOS LaunchAgents — per-user, starts at login / lingers at boot) rather
// than a system unit, so no root is required and state stays in ~/.localterm.
// Crash-only restart (Restart=on-failure === KeepAlive.SuccessfulExit=false):
// the daemon restarts on crash but a clean stop (localterm stop → SIGTERM →
// exit 0) stays stopped. ExecStartPre only waits for tailscale when it's
// installed (`command -v tailscale`), so a pure loopback/ssh-tunnel VPS with no
// tailscale isn't blocked at boot; when it is installed, the wait lets the
// daemon resolve the tailnet URL via `tailscale serve status` so setPublicUrl
// trusts the *.ts.net host before the first request lands.
export const buildSystemdUnitContent = (input: SystemdUnitContentInput): string => {
  // node dir first (a user-installed node shadows system node, matching the
  // launchd plist) then the standard system bins; dedupe so a node living in
  // /usr/local/bin or /usr/bin isn't listed twice.
  const pathEntries = [
    path.dirname(input.execPath),
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ];
  const pathEnv = [...new Set(pathEntries)].join(":");
  return `# Generated by \`localterm install\`. Manage with \`systemctl --user\`.
[Unit]
Description=localterm terminal daemon
Documentation=https://github.com/monotykamary/localterm
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
Environment=HOME=%h
Environment=PATH=${pathEnv}
ExecStartPre=/bin/sh -c 'command -v tailscale >/dev/null 2>&1 || exit 0; for i in $(seq 1 ${input.tailscaleBootWaitSeconds}); do tailscale status --json >/dev/null 2>&1 && exit 0; sleep 1; done; exit 0'
ExecStart=${input.execPath} ${input.cliEntry} start --foreground --port ${input.port} --host ${input.host}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
`;
};

const launchctl = async (...args: string[]): Promise<{ stdout: string; stderr: string }> => {
  return execFileAsync("launchctl", args, { timeout: 10_000 });
};

type PortlessStepResult = { ok: true } | { ok: false; missing: boolean; message: string };

const runPortlessStep = async (args: string[]): Promise<PortlessStepResult> => {
  try {
    await execFileAsync("portless", args, { timeout: PORTLESS_SERVICE_TIMEOUT_MS });
    return { ok: true };
  } catch (error) {
    if (isPortlessMissing(error)) {
      return { ok: false, missing: true, message: args.join(" ") };
    }
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, missing: false, message };
  }
};

const warnPortlessMissing = (): void => {
  console.warn(kleur.yellow("  ⚠ portless not installed"));
  console.warn(kleur.dim("    install: pnpm add -Dw portless  (workspace) or npm i -g portless"));
};

export const setupPortlessProxy = async (): Promise<void> => {
  console.log();
  console.log(kleur.cyan("portless proxy  — named .localhost URLs"));

  // The proxy serving :443 is the only thing that matters; `portless service
  // install` is just boot registration, and it fails spuriously when the proxy
  // is already installed (it shells out to BSD `install` and chokes on existing
  // state). Treat a live proxy as the source of truth: if it's already up,
  // skip the install; otherwise attempt it and re-check liveness before
  // warning, so a genuine "proxy not running" surfaces but the
  // existing-install false-failure stays silent.
  if (await isPortlessProxyLive()) {
    console.log(kleur.green("  ✔ proxy already running (HTTPS on :443)"));
  } else {
    const install = await runPortlessStep(["service", "install"]);
    if (install.ok) {
      console.log(kleur.green("  ✔ proxy service installed (HTTPS on :443, starts at boot)"));
    } else if (install.missing) {
      warnPortlessMissing();
      return;
    } else if (!(await isPortlessProxyLive())) {
      console.warn(
        kleur.yellow("  ⚠ portless proxy not running on :443 — re-run `localterm install`"),
      );
    }
  }

  const trust = await runPortlessStep(["trust"]);
  if (trust.ok) {
    console.log(kleur.green("  ✔ local CA trusted (browsers accept https://*.localhost)"));
  } else if (trust.missing) {
    warnPortlessMissing();
  } else {
    console.warn(kleur.yellow(`  ⚠ portless trust failed: ${trust.message}`));
  }
};

const setupTailscaleServe = async (port: number): Promise<void> => {
  console.log();
  console.log(kleur.cyan("tailscale  — share on your tailnet at https://<node>.ts.net"));
  const route = await configureTailscaleServe(port);
  if (route.registered && route.url) {
    console.log(kleur.green(`  ✔ tailnet URL: ${route.url}`));
    console.log(
      kleur.dim(`    exposed on tailnet at :${TAILSCALE_HTTPS_PORT} (HTTPS cert auto-managed)`),
    );
    return;
  }
  switch (route.reason) {
    case "binary-missing":
      console.warn(kleur.yellow(`  ⚠ tailscale not installed — skipped tailnet exposure`));
      console.warn(kleur.dim(`    install: ${route.hint ?? "https://tailscale.com/download"}`));
      break;
    case "https-disabled":
      console.warn(
        kleur.yellow(`  ⚠ tailscale HTTPS certificates are not enabled on your tailnet`),
      );
      console.warn(
        kleur.dim(
          `    enable: ${route.hint ?? "https://login.tailscale.com/admin/settings/features"}`,
        ),
      );
      console.warn(
        kleur.dim(`    then re-run: ${kleur.bold("localterm install")} to provision the cert`),
      );
      break;
    case "offline":
      console.warn(
        kleur.yellow(
          `  ⚠ tailscale not online — run \`tailscale up\` and re-run \`localterm install\``,
        ),
      );
      break;
    case "serve-mismatch":
    case undefined:
      console.warn(
        kleur.yellow(`  ⚠ could not configure tailscale serve (port ${port} not registered)`),
      );
      break;
  }
};

const reportCdpAvailability = async (): Promise<void> => {
  console.log();
  console.log(kleur.cyan("chromium  — background automation tabs (no focus steal, closeable)"));
  const availability = await probeCdpAvailability(readConfiguredCdpPort());
  if (availability.available) {
    console.log(
      kleur.green(
        `  ✔ debug-enabled ${availability.browserName} detected — automation tabs open in the background`,
      ),
    );
    return;
  }
  console.warn(
    kleur.yellow(
      "  ⚠ no debug-enabled Chromium detected — automation tabs open in the foreground (OS opener)",
    ),
  );
  console.warn(kleur.dim(`    enable: ${CDP_REMOTE_DEBUGGING_HINT}`));
};

type SystemctlResult = { ok: true } | { ok: false; missing: boolean; message: string };

const runSystemctl = async (args: string[]): Promise<SystemctlResult> => {
  try {
    await execFileAsync("systemctl", ["--user", ...args], {
      timeout: SYSTEMD_OPERATION_TIMEOUT_MS,
    });
    return { ok: true };
  } catch (error) {
    const missing = error instanceof Error && (error as NodeJS.ErrnoException).code === "ENOENT";
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, missing, message };
  }
};

const enableSystemdUserUnit = async (): Promise<void> => {
  console.log();
  console.log(kleur.cyan("systemd  — enable + start the user service"));
  const reload = await runSystemctl(["daemon-reload"]);
  if (!reload.ok) {
    if (reload.missing) {
      console.warn(kleur.yellow("  ⚠ systemctl not found on PATH"));
      console.warn(kleur.dim("    the unit file was written; start it with:"));
      console.warn(
        kleur.dim("    systemctl --user daemon-reload && systemctl --user enable --now localterm"),
      );
    } else {
      console.warn(kleur.yellow(`  ⚠ systemctl --user daemon-reload failed: ${reload.message}`));
      console.warn(
        kleur.dim(
          "    no systemd user session? run the commands above manually, and `sudo loginctl enable-linger $USER` so the service starts at boot without an active session",
        ),
      );
    }
    return;
  }
  const enable = await runSystemctl(["enable", "--now", SYSTEMD_USER_UNIT_NAME]);
  if (!enable.ok) {
    console.warn(kleur.yellow(`  ⚠ systemctl --user enable --now failed: ${enable.message}`));
    console.warn(kleur.dim("    run manually: systemctl --user enable --now localterm"));
    return;
  }
  console.log(kleur.green("  ✔ service enabled and started (restarts on crash)"));
  console.log(
    kleur.dim("    for boot without an active session: sudo loginctl enable-linger $USER"),
  );
};

const validateLaunchAgentsDirectory = (): CliError | null => {
  const dir = path.dirname(getLaunchdPlistPath());
  if (!existsSync(dir)) {
    return cliError.installFailed(
      `LaunchAgents directory not found at ${dir}. Is this a valid macOS user account?`,
    );
  }
  return null;
};

const runInstallMac = async (options: InstallOptions): Promise<void> => {
  const plistPath = getLaunchdPlistPath();

  if (existsSync(plistPath)) {
    try {
      await launchctl("unload", plistPath);
    } catch {
      // May not be loaded; that's fine
    }
  }

  const dirValidationError = validateLaunchAgentsDirectory();
  if (dirValidationError !== null) {
    reportCliError(dirValidationError);
    process.exit(exitCodeForCliError(dirValidationError));
    return;
  }

  let portlessDir: string | undefined;
  try {
    const { stdout } = await execFileAsync("/bin/sh", ["-c", "command -v portless"], {
      timeout: PORTLESS_RESOLVE_TIMEOUT_MS,
    });
    const portlessBin = stdout.trim();
    if (portlessBin) portlessDir = path.dirname(portlessBin);
  } catch {
    // portless not installed — daemon announces the loopback surface instead
  }

  const content = buildPlistContent({ ...options, portlessDir });
  writeFileSync(plistPath, content, "utf8");

  try {
    await launchctl("load", plistPath);
  } catch (loadError) {
    const message = loadError instanceof Error ? loadError.message : String(loadError);
    const loadFailError = cliError.installFailed(
      `wrote ${plistPath} but launchctl load failed: ${message}`,
    );
    reportCliError(loadFailError);
    process.exit(exitCodeForCliError(loadFailError));
    return;
  }

  console.log(kleur.green(`✔ launchd service installed`));
  console.log(`  plist:  ${kleur.dim(plistPath)}`);
  console.log(`  node:   ${kleur.dim(process.execPath)}`);
  console.log(`  entry:  ${kleur.dim(cliEntry)}`);
  console.log(`  port:   ${options.port}`);
  console.log(`  host:   ${options.host}`);
  console.log();
  console.log(
    `  ${kleur.bold("RunAtLoad")} + ${kleur.bold("KeepAlive")} enabled — localterm will:`,
  );
  console.log(`    • start automatically at login`);
  console.log(`    • restart immediately if it crashes`);
  console.log();
  console.log(`  remove with ${kleur.bold("localterm uninstall")}`);

  await setupPortlessProxy();
  await setupTailscaleServe(options.port);
  await reportCdpAvailability();
  await setupShellCompletions();
};

const runInstallLinux = async (options: InstallOptions): Promise<void> => {
  const unitDir = getSystemdUserUnitDir();
  mkdirSync(unitDir, { recursive: true });
  const unitPath = getSystemdUserUnitPath();

  const content = buildSystemdUnitContent({
    port: options.port,
    host: options.host,
    execPath: process.execPath,
    cliEntry,
    tailscaleBootWaitSeconds: SYSTEMD_TAILSCALE_BOOT_WAIT_SECONDS,
  });
  writeFileSync(unitPath, content, "utf8");

  console.log(kleur.green(`✔ systemd user unit installed`));
  console.log(`  unit:    ${kleur.dim(unitPath)}`);
  console.log(`  node:    ${kleur.dim(process.execPath)}`);
  console.log(`  entry:   ${kleur.dim(cliEntry)}`);
  console.log(`  port:    ${options.port}`);
  console.log(`  host:    ${options.host}`);
  console.log();
  console.log(
    `  ${kleur.bold("WantedBy=default.target")} + ${kleur.bold("Restart=on-failure")} — localterm will:`,
  );
  console.log(`    • start at login (and at boot with \`loginctl enable-linger\`)`);
  console.log(`    • restart immediately if it crashes`);

  await enableSystemdUserUnit();
  await setupTailscaleServe(options.port);
  await reportCdpAvailability();
  await setupShellCompletions();
  console.log();
  console.log(`  remove with ${kleur.bold("localterm uninstall")}`);
};

export const runInstall = async (options: InstallOptions): Promise<void> => {
  writeCommandSpec();
  if (process.platform === "darwin") {
    await runInstallMac(options);
    return;
  }
  if (process.platform === "linux") {
    await runInstallLinux(options);
    return;
  }
  const platformError = cliError.installFailed(
    "auto-start is only available on macOS (launchd) and Linux (systemd user unit). " +
      "On other platforms, run `localterm start --foreground` under your init system manually.",
  );
  reportCliError(platformError);
  process.exit(exitCodeForCliError(platformError));
};

const runUninstallMac = async (): Promise<void> => {
  const plistPath = getLaunchdPlistPath();

  if (!existsSync(plistPath)) {
    console.log(kleur.dim("launchd service is not installed."));
    return;
  }

  try {
    await launchctl("unload", plistPath);
  } catch {
    // May not be loaded; that's fine
  }

  await removeTailscaleServe();
  await teardownShellCompletions();

  try {
    unlinkSync(plistPath);
  } catch (unlinkError) {
    const message = unlinkError instanceof Error ? unlinkError.message : String(unlinkError);
    const removeFailError = cliError.installFailed(
      `unloaded service but failed to remove ${plistPath}: ${message}`,
    );
    reportCliError(removeFailError);
    process.exit(exitCodeForCliError(removeFailError));
    return;
  }

  console.log(kleur.green("✔ launchd service uninstalled"));
  console.log(`  removed ${kleur.dim(plistPath)}`);
};

const runUninstallLinux = async (): Promise<void> => {
  const unitPath = getSystemdUserUnitPath();

  if (existsSync(unitPath)) {
    const disable = await runSystemctl(["disable", "--now", SYSTEMD_USER_UNIT_NAME]);
    if (!disable.ok) {
      if (disable.missing) {
        console.log(kleur.dim("systemctl not found on PATH; removing the unit file only."));
      } else {
        console.warn(kleur.yellow(`  ⚠ systemctl --user disable --now failed: ${disable.message}`));
      }
    }
  }

  await removeTailscaleServe();
  await teardownShellCompletions();

  if (!existsSync(unitPath)) {
    console.log(kleur.dim("systemd user unit is not installed."));
    return;
  }

  try {
    unlinkSync(unitPath);
  } catch (unlinkError) {
    const message = unlinkError instanceof Error ? unlinkError.message : String(unlinkError);
    const removeFailError = cliError.installFailed(`failed to remove ${unitPath}: ${message}`);
    reportCliError(removeFailError);
    process.exit(exitCodeForCliError(removeFailError));
    return;
  }

  const reload = await runSystemctl(["daemon-reload"]);
  if (!reload.ok && !reload.missing) {
    console.warn(kleur.dim(`  ⚠ systemctl --user daemon-reload failed: ${reload.message}`));
  }

  console.log(kleur.green("✔ systemd user unit uninstalled"));
  console.log(`  removed ${kleur.dim(unitPath)}`);
};

export const runUninstall = async (): Promise<void> => {
  if (process.platform === "darwin") {
    await runUninstallMac();
    return;
  }
  if (process.platform === "linux") {
    await runUninstallLinux();
    return;
  }
  const platformError = cliError.installFailed(
    "auto-start is only available on macOS (launchd) and Linux (systemd user unit).",
  );
  reportCliError(platformError);
  process.exit(exitCodeForCliError(platformError));
};
