packages:
  - "apps/*"
  - "apps/harness/*"
  - "packages/*"

allowBuilds:
  "@google/genai": true
  msw: false
  node-pty: true
  protobufjs: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@google/genai"
  - esbuild
  - node-pty
  - protobufjs
  - sharp
  - spawn-sync
  - unrs-resolver

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.1

patchedDependencies:
  "@xterm/addon-webgl@0.20.0-beta.286": patches/@xterm__addon-webgl@0.20.0-beta.286.patch
  "node-pty@1.1.0": "patches/node-pty@1.1.0.patch"
