packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - node-pty
  - sharp
  - spawn-sync
  - unrs-resolver

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.12

patchedDependencies:
  "node-pty@1.1.0": "patches/node-pty@1.1.0.patch"
