import type { IUnicodeVersionProvider } from "@xterm/xterm";
import { bunWidthOverride, isWideJoiningMarkOverride } from "./bun-width-overrides";

// charProperties packs values as (charKind << 3) | (width << 1) | shouldJoin,
// matching UnicodeService.createPropertyValue in @xterm/xterm.
const WIDTH_BITS = 0b110;
const WIDTH_WIDE = 2 << 1;
const SHOULD_JOIN = 0b1;

/**
 * Wraps the "15-graphemes" provider and corrects codepoints where its
 * Unicode data disagrees with Bun.stringWidth, so terminal wrapping stays
 * in lockstep with the app's repaint math during streaming.
 *
 * The override table is auto-generated by scripts/generate-bun-width-table.ts
 * which compares Bun.stringWidth against the addon's wcwidth for every
 * relevant codepoint. Re-run that script when Bun's width table changes.
 *
 * Width-0 overrides (invisible format chars) apply in both buffers since they
 * prevent cursor-desync in all contexts. Width-1 and width-2 overrides are
 * normal-buffer-only: full-screen TUIs (vim, less, tmux) run in the alternate
 * buffer and use correct wcwidth, so their combining-mark joins and widths
 * must be left intact.
 *
 * The base provider's charProperties uses the preceding value's charKind to
 * decide grapheme boundaries (via UC.shouldJoin). If we modify the return
 * value and let it become the next call's preceding, the base misclassifies
 * subsequent characters. To avoid this, we shadow-keep what the base actually
 * returned and feed that back to the base on the next call, so the base always
 * sees its own charKind chain undisturbed.
 */
export class EmojiWidthUnicodeProvider implements IUnicodeVersionProvider {
  public readonly version = "15-graphemes-emoji";

  private readonly base: IUnicodeVersionProvider;
  private readonly isNormalBufferActive: () => boolean;

  // Shadow of what the base provider returned on the last charProperties call.
  // This is fed back to the base as `preceding` so the base's grapheme-break
  // analysis always sees its own charKind chain — never our modified values.
  private basePreceding = 0;

  constructor(base: IUnicodeVersionProvider, isNormalBufferActive: () => boolean = () => true) {
    this.base = base;
    this.isNormalBufferActive = isNormalBufferActive;
  }

  public wcwidth(codepoint: number): 0 | 1 | 2 {
    const override = bunWidthOverride(codepoint);
    if (override === 0) return 0;
    if (this.isNormalBufferActive()) {
      if (override === 1) return 1;
      if (override === 2) return 2;
    }
    return this.base.wcwidth(codepoint);
  }

  public charProperties(codepoint: number, _preceding: number): number {
    // Always feed the base its own last return so grapheme analysis
    // stays on the unmodified charKind chain.
    const props = this.base.charProperties(codepoint, this.basePreceding);
    this.basePreceding = props;

    const override = bunWidthOverride(codepoint);

    if (override === 0) {
      // Encode like the addon encodes Extend combining marks: join into the
      // preceding cell and report the cluster's width (the preceding cell's).
      // InputHandler.print advances the cursor for any non-joining codepoint
      // even at width 0, so a bare width override would still eat a column.
      const precedingWidth = _preceding & WIDTH_BITS;
      return (props & ~WIDTH_BITS) | precedingWidth | SHOULD_JOIN;
    }

    if (!this.isNormalBufferActive()) return props;

    if (override === 1) {
      // Bun says width 1 standalone; addon says width 0 joining. Report as
      // standalone width-1 so cursor advances match Bun.
      return (props & ~WIDTH_BITS & ~SHOULD_JOIN) | (1 << 1);
    }

    if (override === 2) {
      if (isWideJoiningMarkOverride(codepoint)) {
        return (props & ~WIDTH_BITS) | WIDTH_WIDE | SHOULD_JOIN;
      }
      return (props & ~WIDTH_BITS & ~SHOULD_JOIN) | WIDTH_WIDE;
    }

    return props;
  }
}
