// WebSocket with binaryType="arraybuffer" delivers event.data as an ArrayBuffer
// in production. instanceof ArrayBuffer is the right check in a single realm,
// but tests pass binary frames generated by Node's TextEncoder — those are
// ArrayBuffers from Node's realm, not the jsdom/web realm this code evaluates
// against, so instanceof returns false for them. The canonical class-string
// from Object.prototype.toString is realm-agnostic and so works in both. We
// short-circuit on the truthy instanceof first since it's the common path.
const objectToString = Object.prototype.toString;

const isBinaryMessageData = (data: unknown): data is ArrayBuffer =>
  data instanceof ArrayBuffer || objectToString.call(data) === "[object ArrayBuffer]";

export { isBinaryMessageData };
