import fs from "node:fs";
import path from "node:path";
import type { Process } from "./types.js";
import type { SecretBackend } from "./secret-backend.js";
import { ACTIVITY_WATCHED_PROGRAMS } from "./constants.js";

interface ProgramSecret {
  envVar: string;
  name: string;
}

const shellQuote = (value: string): string => `'${value.replace(/'/g, "'\\''")}'`;

const buildProcessSecretIndex = (
  processes: readonly Process[],
  envVarByName: Map<string, string>,
): Map<string, ProgramSecret[]> => {
  const index = new Map<string, ProgramSecret[]>();
  for (const process of processes) {
    const resolved: ProgramSecret[] = [];
    for (const secretName of process.requestedSecrets) {
      const envVar = envVarByName.get(secretName);
      if (envVar) resolved.push({ envVar, name: secretName });
    }
    if (resolved.length > 0) index.set(process.name, resolved);
  }
  return index;
};

export const buildShimContent = (
  program: string,
  shimsDir: string,
  backend: Pick<SecretBackend, "nativeHelperProtocol" | "shimResolveSnippet">,
  helperPath: string | undefined,
  secrets: readonly ProgramSecret[],
  activityFile?: string,
): string => {
  if (helperPath !== undefined && !path.isAbsolute(helperPath)) {
    throw new Error("secretHelperPath must be an absolute path when supplied");
  }
  const lines: string[] = [
    "#!/bin/sh",
    "# localterm shim for " + program + ". Generated by localterm-server; do not edit.",
    `_shim_dir=${shellQuote(shimsDir)}`,
  ];
  if (activityFile) lines.push(`_activity_file=${shellQuote(activityFile)}`);
  lines.push(
    "_rest=",
    "_oldifs=$IFS",
    "IFS=:",
    "for _d in $PATH; do",
    '  [ "$_d" = "$_shim_dir" ] && continue',
    "  _rest=${_rest:+$_rest:}$_d",
    "done",
    "IFS=$_oldifs",
    `_real=$(PATH=$_rest command -v ${shellQuote(program)}) || { printf 'localterm: ${program.replace(/'/g, "'\\''")} not found on PATH\\n' >&2; exit 127; }`,
  );

  const useNativeHelper =
    secrets.length > 0 &&
    backend.nativeHelperProtocol === "localterm-keychain-v1" &&
    helperPath !== undefined;
  if (!useNativeHelper) {
    lines.push(...secrets.map((secret) => backend.shimResolveSnippet(secret.name, secret.envVar)));
  }
  const command = useNativeHelper
    ? [
        shellQuote(helperPath),
        ...secrets.flatMap((secret) => [shellQuote(secret.envVar), shellQuote(secret.name)]),
        "--",
        '"$_real"',
        '"$@"',
      ].join(" ")
    : '"$_real" "$@"';
  if (activityFile) {
    lines.push(
      command,
      "_rc=$?",
      'printf \'%s\\n\' "$PWD" > "$_activity_file" 2>/dev/null || :',
      "exit $_rc",
    );
  } else {
    lines.push(`exec ${command}`);
  }
  lines.push("");
  return lines.join("\n");
};

const writeShimAtomically = (shimPath: string, content: string): void => {
  const temporaryPath = `${shimPath}.tmp-${process.pid}-${Math.random().toString(16).slice(2)}`;
  try {
    fs.writeFileSync(temporaryPath, content, { flag: "wx", mode: 0o700 });
    fs.chmodSync(temporaryPath, 0o700);
    fs.renameSync(temporaryPath, shimPath);
  } finally {
    fs.rmSync(temporaryPath, { force: true });
  }
};

export const regenerateShims = (
  processes: readonly Process[],
  envVarByName: Map<string, string>,
  shimsDir: string,
  backend: Pick<SecretBackend, "nativeHelperProtocol" | "shimResolveSnippet" | "supported">,
  activityDir: string,
  helperPath?: string,
  activityWatched: readonly string[] = ACTIVITY_WATCHED_PROGRAMS,
): void => {
  if (helperPath !== undefined && !path.isAbsolute(helperPath)) {
    throw new Error("secretHelperPath must be an absolute path when supplied");
  }
  if (!backend.supported) {
    try {
      for (const name of fs.readdirSync(shimsDir)) {
        fs.rmSync(path.join(shimsDir, name), { force: true });
      }
    } catch {
      // The directory has not been created yet.
    }
    return;
  }

  const processIndex = buildProcessSecretIndex(processes, envVarByName);

  const wantedPrograms = new Set<string>(processIndex.keys());
  for (const program of activityWatched) wantedPrograms.add(program);
  const wantedShims = [...wantedPrograms].map((program) => {
    const activityFile = activityWatched.includes(program)
      ? path.join(activityDir, program)
      : undefined;
    return {
      content: buildShimContent(
        program,
        shimsDir,
        backend,
        helperPath,
        processIndex.get(program) ?? [],
        activityFile,
      ),
      program,
    };
  });

  fs.mkdirSync(shimsDir, { recursive: true, mode: 0o700 });
  fs.mkdirSync(activityDir, { recursive: true, mode: 0o700 });
  for (const shim of wantedShims) {
    writeShimAtomically(path.join(shimsDir, shim.program), shim.content);
  }
  for (const name of fs.readdirSync(shimsDir)) {
    if (!wantedPrograms.has(name)) fs.rmSync(path.join(shimsDir, name), { force: true });
  }
};

export const shimPathPrependLine = (shimsDir: string): string => {
  const escaped = shimsDir.replace(/'/g, "'\\''");
  return `[ -d '${escaped}' ] && PATH='${escaped}:'"$PATH" && export PATH`;
};
