import fs from "node:fs";
import path from "node:path";
import type { Process } from "./types.js";
import type { SecretBackend } from "./secret-backend.js";

interface ProgramSecret {
  envVar: string;
  name: string;
}

// Build the index the shim generator consumes: process name -> the secrets that
// process should receive (in policy order, so the shim's env assignments are
// stable across regenerations). A process's requestedSecrets are resolved to
// {envVar, name} via `envVarByName`; a name that no longer exists in the store
// (a deleted secret the cascading delete missed, or a stale process file) is
// skipped so a shim never references a missing secret. A process whose
// requestedSecrets resolve to nothing (empty selection, or only deleted
// secrets) is omitted entirely so it gets no shim — matching the pre-flip
// behavior where a program no secret referenced had no shim, and the
// stale-shim sweep then removes any shim it previously had.
const buildProcessSecretIndex = (
  processes: readonly Process[],
  envVarByName: Map<string, string>,
): Map<string, ProgramSecret[]> => {
  const index = new Map<string, ProgramSecret[]>();
  for (const process of processes) {
    const resolved: ProgramSecret[] = [];
    for (const secretName of process.requestedSecrets) {
      const envVar = envVarByName.get(secretName);
      if (envVar) resolved.push({ envVar, name: secretName });
    }
    if (resolved.length > 0) index.set(process.name, resolved);
  }
  return index;
};

// The self-contained POSIX shim for one program. Strips its own directory from
// PATH so `command -v` resolves the REAL binary (not this shim — recursion),
// then resolves each secret via the backend's snippet and execs the real
// binary with the non-empty ones exported. The shim runs in the PTY where the
// user's rc files have already built the full PATH (homebrew, mise, …), so
// `command -v <program>` finds the real binary the user installed; only the
// shims dir (prepended by localterm's shell hook AFTER the rc files run) is
// excluded. `_shim_dir` is baked as a literal so the strip-by-equality match
// is exact even if $HOME differs from the daemon's view.
export const buildShimContent = (
  program: string,
  shimsDir: string,
  resolveSnippet: string,
): string => {
  const escapedProgram = program.replace(/'/g, "'\\''");
  const escapedShimsDir = shimsDir.replace(/'/g, "'\\''");
  return [
    "#!/bin/sh",
    "# localterm shim for " + program + ". Generated by localterm-server; do not edit.",
    "# Strips this shim's own directory from PATH so `command -v` resolves the",
    "# real binary instead of recursing into this shim. localterm's shell hook",
    "# prepends the shims dir after the user's rc files run, so it is first on PATH.",
    "_shim_dir='" + escapedShimsDir + "'",
    "_rest=",
    "_oldifs=$IFS",
    "IFS=:",
    "for _d in $PATH; do",
    '  [ "$_d" = "$_shim_dir" ] && continue',
    "  _rest=${_rest:+$_rest:}$_d",
    "done",
    "IFS=$_oldifs",
    "_real=$(PATH=$_rest command -v '" +
      escapedProgram +
      "') || { printf 'localterm: " +
      escapedProgram +
      " not found on PATH\\n' >&2; exit 127; }",
    resolveSnippet,
    'exec "$_real" "$@"',
    "",
  ].join("\n");
};

// Regenerate all shims for the current policy: one shim per process, and
// stale shims (process names no longer present) removed. Called on daemon start
// and after every policy change. The shims dir is localterm-owned
// (~/.localterm/shims) and contains only generated shims, so removing any file
// not in the wanted set is safe.
export const regenerateShims = (
  processes: readonly Process[],
  envVarByName: Map<string, string>,
  shimsDir: string,
  backend: SecretBackend,
): void => {
  if (!backend.supported) {
    // No backend: clear any stale shims and leave nothing behind, so the
    // feature is inert rather than emitting shims that resolve to nothing.
    try {
      for (const name of fs.readdirSync(shimsDir)) {
        fs.rmSync(path.join(shimsDir, name), { force: true });
      }
    } catch {
      // dir absent — nothing to clean
    }
    return;
  }

  const processIndex = buildProcessSecretIndex(processes, envVarByName);
  fs.mkdirSync(shimsDir, { recursive: true, mode: 0o700 });
  const wantedPrograms = new Set(processIndex.keys());

  for (const name of fs.readdirSync(shimsDir)) {
    if (!wantedPrograms.has(name)) {
      fs.rmSync(path.join(shimsDir, name), { force: true });
    }
  }

  for (const [program, programSecrets] of processIndex) {
    const resolveSnippet = programSecrets
      .map((secret) => backend.shimResolveSnippet(secret.name, secret.envVar))
      .join("\n");
    const content = buildShimContent(program, shimsDir, resolveSnippet);
    const shimPath = path.join(shimsDir, program);
    fs.writeFileSync(shimPath, content, { mode: 0o700 });
    // writeFileSync's mode only applies on create; re-chmod so a rewrite of an
    // existing shim with wrong perms is corrected.
    fs.chmodSync(shimPath, 0o700);
  }
};

// The line localterm's shell hook runs AFTER the user's rc files to prepend
// the shims dir to PATH. Running after the rc files is the point: the user's
// rc commonly re-prepends homebrew/mise, which would push a daemon-time PATH
// entry down and let the real binary shadow the shim. The hook runs last, so
// the shims dir wins. The dir's existence gates the prepend (empty feature =
// no PATH pollution).
export const shimPathPrependLine = (shimsDir: string): string => {
  const escaped = shimsDir.replace(/'/g, "'\\''");
  return `[ -d '${escaped}' ] && PATH='${escaped}:'"$PATH" && export PATH`;
};
